version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: median
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

volumes:
  postgres:
  app:
